---
title       : Describing:"When Can I (legally) Drive" Shiny_app.
subtitle    : Developing Data Products, Assignment week 4.
author      : HagenC
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
ext_widgets: {rCharts: [libraries/nvd3]}
---


## Motivation

**"When can I (legally)drive?"** is an Shiny-app that calculates the blood alcohol level (permille),
the units consumed and the time in hours before you can legally drive.

The app can give you an idea what a couple of beers or a glass of wine will do to you!

The calculations are described in the following slides.


---  

## Blood alcohol level (concentration)

The alchohol blood level is calculated as: grams of alcohol / (body weight in Kg * body water fraction).
The body water fraction is 70% for males and 60% for females. 

If we consider a person drinking 3 beers of 4.6 % alchohol the blood alcohol dependency on body weight and sex can be illustrated as below: 

```{r echo = F, results = 'asis'}
suppressPackageStartupMessages(require(rCharts))
gAlco <- 1000*0.046
chart <- data.frame(50:120)
colnames(chart)[1] <- "Kg"
chart$gAlco <- gAlco
chart$female <- 0.6
chart$male <- 0.7
chart$Pmale <- chart$gAlco/(chart$Kg*chart$male)
chart$Pfemale <- chart$gAlco/(chart$Kg*chart$female)
male <- subset(chart  , select = c("Kg", "Pmale"))
male$sex <- "Male"
colnames(male)[2] <- "Pro"
female <- subset(chart  , select = c("Kg", "Pfemale"))
female$sex <- "Female"
colnames(female)[2] <- "Pro"
DB <- rbind(male, female)
#haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Pro ~ Kg, group = "sex", type = 'multiBarChart',
  data = DB)
n1$xAxis(axisLabel = "Body weight (Kg)")
n1$chart(margin = list(left =100))
n1$yAxis(axisLabel = "Blood Alcohol Level (Permille)")
n1$print('chart1')
```

--- .classe 

## Time before reaching the legal blood alchohol level.

The legal blood alcohol level is dependent on country/state law. In Denmark it is 0.5 permille and in Sweden 0.0.

To calulate the time before reaching legal blood alcohol level I use the the widely accepted alchohol metabolizing constant of 0.15 grams/hour. 

Calculating the grams of alcohol in your body and substratc the legal amount of alcohol in grams (that is dependent on body weight and sex) we can calculate the time before the surplus alcohold is metabolized. 

A unit of alcohol is 12g so it will take 12/0.15 = 80 hours to metabolize one unit, no matter your body weight or sex. However, it is actually influenced by whether you have a full stomach or not. If you have eaten, the alcohol metabolism is FASTER. The reverse is true for the alcohol absorbtion that is SLOWER on a full stomach. Absorption is also influenced on sex and body weight. 

Unfortunately, there are no measures of these phenomenons as we are not sure why it is so. Thus, it is ignored in the calculations. 



--- .classe 

## An App without an Disclaimer?: I dont think so:

So...

Disclaimer:  This is only a rough estimate based on population averages and does not take into account existing disease states, drug interactions, or age.




